---
title: "Final"
author: "dan crowley"
date: "4/28/2020"
output: pdf_document
---

```{r }
library(ape)
library(phylofactor)
library(tidyverse)
```

```{r}

sim = (seq(0.000001,100,10)) #must be the same as line 11
eps = (seq(0.000001,100,10))
error <- matrix(0, length(sim)*length(eps), 14)
index = 0
```

```{r}


set.seed(Sys.time())
num= 50 #rpois(1,60)
tree <-rtree(num)
tree$tip.label <- as.character(1:num)
drop_tips = num/20 # determines ratio of test to training data 

#determine max groups
max_groups <- 2*num-2

#choose a clade of the good length, we want to make sure its not monophyletic 
clade1 = 0
clade2 = 0

while((length(clade1) < num / 3) | (length(clade2) < num / 3))
{
  #grab clades
  samp = sample(max_groups, 1)
  clade1 = getPhyloGroups(tree)[samp][1][[1]][[1]]
  clade2 = getPhyloGroups(tree)[samp][1][[1]][[2]]
}

#randomly generate data                                            
BodySize <-rlnorm(num, sdlog = 1.6)
BodySize[clade1] <-rlnorm(length(clade1), sdlog = 1.6)*5

#create a data matrix, with the body size, tip labels, and a basis function of all 1s
BodySize = as.data.frame(cbind(BodySize, tree$tip.label, basis = 1, intercept = 1))
BodySize <- BodySize %>%
  dplyr::mutate(Species=  as.character(V2)) %>%
  dplyr::select(-V2)

#now wegenerate the missing data.
#these are species we haven't observed data for
#in this simulation around 1/3 of the data are missing

#num_miss = 1 + rpois(1,nrow(train_BodySize)/2.5)
num_miss = nrow(BodySize)/3
#num_miss = rpois(1,10)  
miss_tip = sample(tree$tip.label, num_miss)

#create missing body size variable
BodySize$BodySize_miss = BodySize$BodySize
BodySize$basis_miss = BodySize$basis
BodySize$intercept_miss = BodySize$intercept

#create a new variable, and label the boddy size and basis functions NA for these tips
BodySize[(BodySize$Species %in% miss_tip),]$BodySize_miss = NA
BodySize[(BodySize$Species %in% miss_tip),]$basis_miss = NA
BodySize[(BodySize$Species %in% miss_tip),]$intercept_miss = NA

BodySize$basis = as.numeric(BodySize$basis)
BodySize$BodySize = as.numeric(as.character(BodySize$BodySize))
BodySize$intercept = as.numeric(BodySize$intercept)

```


#grab a sample of N tips for the testing tree
```{r }
test_tree <- ape::drop.tip(tree,tree$tip.label[!(tree$tip.label %in% sample(tree$tip.label, drop_tips))])
train_tree <- ape::drop.tip(tree,tree$tip.label[(tree$tip.label %in% test_tree$tip.label)])
```

#should be equal to 0

```{r }
sum(test_tree$tip.label %in% train_tree$tip.label) == 0
sum(train_tree$tip.label %in% test_tree$tip.label) == 0
num - (length(train_tree$tip.label) + length(test_tree$tip.label)) == 0

```


#now, split the dataset into the training and testing datasets

```{r}

train_BodySize = BodySize %>% 
  dplyr::filter(Species %in% train_tree$tip.label)

test_BodySize = BodySize %>% 
  dplyr::filter(Species %in% test_tree$tip.label)

```

#should both be true:
```{r}

sum(train_BodySize$Species %in% test_BodySize$Species) == 0
sum(test_BodySize$Species %in% train_BodySize$Species) == 0

train_BodySize$basis_miss = as.numeric(train_BodySize$basis_miss)
train_BodySize$BodySize_miss = as.numeric(as.character(train_BodySize$BodySize_miss))
train_BodySize$intercept_miss = as.numeric(train_BodySize$intercept_miss)

```


```{r}

test_BodySize <- test_BodySize %>%
  dplyr::mutate(intercept = as.numeric(as.character(intercept))) %>%
  dplyr::mutate(BodySize = as.numeric(as.character(BodySize))) %>%
  dplyr::mutate(basis = as.numeric(as.character(basis)))

train_BodySize$basis_miss = as.numeric(as.character(train_BodySize$basis_miss))
train_BodySize$intercept_miss = as.numeric(as.character(train_BodySize$intercept_miss))
train_BodySize$train_BodySize_miss = as.numeric(as.character(train_BodySize$BodySize_miss))

```

```{r}

ggtree::ggtree(tree, branch.length = 'none', layout = 'circular') + 
  ggtree::geom_tippoint(size=.25*as.numeric(BodySize$BodySize),col='blue')  +
  ggtree::geom_tippoint(size=.23*as.numeric(as.character(BodySize$BodySize_miss)),col='red') +
  ggtree::geom_tiplab()  

```


```{r}


for( x in sim)
{
  print(paste("X =", x))
  epsilon = x
  j=1
  for(j in eps)
  {

    #switch things up, keep the same tree, but grab different training and tesing everytime
    
    print(paste("j =", j))
    index = index + 1
    delta = 1 #delta is a control parameter for the bayesian model. as it gets bigger the estimates shrink to 0
    delta = delta*(j)
    #delta = delta*j
    #print(num)
    source('6th_attempt.R')
  
    #create the predictions based on mu_map
    #create a new variable, and label the boddy size and basis functions NA for these tips
  
    #we need to test the max estimate, and the mle estimate
    #when there are no missing data, they find the same split point
    #however, when the tips are missing they tend to get different
    #we should probably test them both on the actual split point..

    #first, identify the two groups pulled out by GPF in the training dataset
  
    #grp1 = train_tree$tip.label[gpf_results$groups[1][[1]][[1]]]
    #grp2 = train_tree$tip.label[gpf_results$groups[1][[1]][[2]]]
    min = which.min(results[,1])
    min_2 = which.min(results[,7])
  
  # results[i,1] <-  sse_map
  # results[i,2] <-  beta_ridge[2]
  # results[i,3] <-  beta_ridge[1]
  # results[i,4] <-  N1
  # results[i,5] <-  N2
  # results[i,6] <-  theta_2
  # results[i,7] <-  SSE_train
    
   error[index,1]  <-  results[min,1] #sse 
   error[index,2]  <-  results[min,2]
   error[index,3]  <-  results[min,3]
   error[index,4]  <-  results[min,4]
   error[index,5]  <-  results[min,5]
   error[index,6]  <-  results[min,6]
   error[index,7]  <-  delta
   error[index,8]  <-  epsilon
   error[index,9]  <-  sse_gpf
   error[index,10] <-  results[min,7]
   error[index,11] <-  results[min_2,1]
   error[index,12] <-  results[min_2,7]
   error[index,13] <-  min
   error[index,14] <-  min_2
   
   print(error[index,])
  }
}

```


```{r}


error %>%
  as.data.frame() %>%
  ggplot2::ggplot(aes(V7, V8)) +
  ggplot2::geom_tile(aes(fill= as.numeric(V1 - V9) )) +
  ggplot2::xlab("delta") +
  ggplot2::ylab("epsilon")

plot(y = error[,1] - error[,9], x = (error[,6]), col = rgb(red = error[,13]/max(error[,13]), green = 0, blue = 1, alpha = 0.9)) 

plot(y = log(error[,1]), x = error[,6], col = rgb(red = error[,13]/max(error[,13]), green = 0, blue = 1, alpha = 0.9)) 

error[,13]
error[,14]

train_BodySize[getPhyloGroups(train_tree)[unique(error[,13])[1]][[1]][[1]],]$Species
train_BodySize[getPhyloGroups(train_tree)[unique(error[,13])[2]][[1]][[1]],]$Species
train_BodySize[getPhyloGroups(train_tree)[unique(error[,13])[3]][[1]][[1]],]$Species
train_BodySize[getPhyloGroups(train_tree)[unique(error[,13])[4]][[1]][[1]],]$Species
train_BodySize[getPhyloGroups(train_tree)[unique(error[,13])[5]][[1]][[1]],]$Species
train_BodySize[getPhyloGroups(train_tree)[unique(error[,13])[6]][[1]][[1]],]$Species
train_BodySize[getPhyloGroups(train_tree)[unique(error[,13])[7]][[1]][[1]],]$Species
train_BodySize[getPhyloGroups(train_tree)[unique(error[,13])[8]][[1]][[1]],]$Species
train_BodySize[getPhyloGroups(train_tree)[unique(error[,13])[9]][[1]][[1]],]$Species
train_BodySize[getPhyloGroups(train_tree)[unique(error[,13])[10]][[1]][[1]],]$Species
train_BodySize[getPhyloGroups(train_tree)[unique(error[,13])[11]][[1]][[1]],]$Species
train_BodySize[getPhyloGroups(train_tree)[unique(error[,13])[12]][[1]][[1]],]$Species

#theta_2 =  epsilon * exp(-delta * N1 * N2) 

BodySize[clade2,]$Species 
BodySize[clade1,]$Species 

ggtree::ggtree(tree, branch.length = 'none', layout = 'circular') + 
  ggtree::geom_tippoint(size=.15*as.numeric(BodySize$BodySize),col='blue')  +
  ggtree::geom_tippoint(size=.10*as.numeric(as.character(BodySize$BodySize_miss)),col='red') +
  ggtree::geom_tiplab()  

ggtree::ggtree(train_tree, branch.length = 'none', layout = 'fan') + 
  ggtree::geom_tippoint(size=.23*as.numeric(as.character(train_BodySize$BodySize_miss)),col='red') +
  ggtree::geom_tiplab() 

# plot((error[,1]), type = 'l', lwd = 5, col = rgb(red = 0, green = 0, blue = 1, alpha = 0.9))
# plot(error[,1], error[,7], lwd = 5, col = rgb(red = 0, green = 0, blue = 1, alpha = 0.9))
# plot(error[,1], error[,8], lwd = 5, col = rgb(red = 0, green = 0, blue = 1, alpha = 0.9))
# plot(error[,1], error[,6], lwd = 5, col = rgb(red = 0, green = 0, blue = 1, alpha = 0.9))
# 
plot(y =error[,3], x=error[,6], lwd = 5, col = rgb(red = 0, green = 0, blue = 1, alpha = 0.9))
# 
# plot((error[,10]), type = 'l', lwd = 5, col = rgb(red = 1, green = 0, blue = 1, alpha = 0.9))
# 
# plot((error[,11]), type = 'l', lwd = 5, col = rgb(red = 0, green = 0, blue = 1, alpha = 0.9))
# plot((error[,12]), type = 'l', lwd = 5, col = rgb(red = 0, green = 0, blue = 1, alpha = 0.9))

plot(error[,11] - error[,9], col = rgb(red = 0, green = 0, blue = 1, alpha = 0.9))                         

```




